WITH random_data AS (
    SELECT
        (array['John', 'Jane', 'Michael', 'Emily', 'Chris', 'Jessica', 'Daniel', 'Ashley', 'Matthew', 'Sarah'])[ceil(random() * 10)] AS first_name,
        (array['Doe', 'Smith', 'Johnson', 'Brown', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris'])[ceil(random() * 10)] AS last_name,
        (array['123 Main St', '456 Elm St', '789 Maple Ave', '101 Pine St', '202 Oak St'])[ceil(random() * 5)] AS street_address,
        (array['Anytown', 'Springfield', 'Riverside', 'Greenville', 'Fairview'])[ceil(random() * 5)] AS property_city,
        (array['CA', 'NY', 'TX', 'FL', 'IL'])[ceil(random() * 5)] AS property_state,
        (array['90210', '10001', '73301', '33101', '60601'])[ceil(random() * 5)] AS zip,
        '555-' || lpad(floor(random() * 1000)::text, 3, '0') || '-' || lpad(floor(random() * 10000)::text, 4, '0') AS cell_phone,
        '555-' || lpad(floor(random() * 1000)::text, 3, '0') || '-' || lpad(floor(random() * 10000)::text, 4, '0') AS home_phone,
        (random() * (500000.00 - 100000.00) + 100000.00)::numeric(10, 2) AS desired_loan_amt,
        (random() * (700000.00 - 300000.00) + 300000.00)::numeric(10, 2) AS property_value,
        (random() * (5.00 - 2.00) + 2.00)::numeric(4, 3) AS first_mort_rate,
        (random() * (300000.00 - 50000.00) + 50000.00)::numeric(10, 2) AS first_mort_balance
)
INSERT INTO app.free_rate_update (
    id, created_date, leads_prop_value, rid, request_id, ssn, loan_purpose, property_type,
    credit_rating, desired_rate_type, cashout, property_value, first_mort_balance,
    first_mort_rate, rate_type1, new_home_value, est_down_payment, property_use,
    purch_with_agent, second_mort_balance, user_text1, current_fha_loan, originated_before,
    signed_contract, veteran_military, found_home, purch_agreement, first_name, last_name,
    email, street_address, property_city, property_state, zip, cell_phone, home_phone,
    other_phone, desired_loan_amt, specials, ltv, method, adnetwork, blockclient,
    campaign_id, current_va_loan, age_62_or_older
) 
SELECT 
    nextval('global_lead_id_seq'), 
    (now() AT TIME ZONE 'MST'), 
    350000.00, 
    'RID' || lpad(floor(random() * 1000000)::text, 6, '0'),
    'REQ' || lpad(floor(random() * 1000000)::text, 6, '0'),
    '123-45-6789', 
    'Refinance', 
    'Single Family', 
    'Excellent', 
    'Fixed',
    'No', 
    property_value, 
    first_mort_balance, 
    first_mort_rate, 
    'Fixed', 
    NULL, 
    NULL, 
    'Primary Residence',
    'No', 
    0.00, 
    'Yes', 
    'No', 
    'Yes', 
    'No', 
    'No', 
    NULL, 
    NULL,
    first_name,
    last_name,
    lower(first_name || '.' || last_name || '@email.com'), 
    street_address, 
    property_city, 
    property_state, 
    zip, 
    cell_phone,
    home_phone, 
    NULL, 
    desired_loan_amt, 
    NULL, 
    81.25, 
    'Online', 
    'AdNetwork1', 
    'Client1',
    'CAMP001', 
    'No', 
    'No'
FROM random_data;
