export interface Lead {
  id?: number;
  globalid: string;
  created_date: string;
  lastContact: string | null;
  first_name: string;
  last_name: string;
  phone_primary: string | null;
  property_state: string;
  property_type: string;
  first_mortgage_balance: number;
  veteran_status: string;
  leadStatus: string;
  lead_source?: string;
  middle_name?: string | null;
  suffix?: string | null;
  email?: string;
  ssn?: string;
  birth_date?: string | null;
  phone_secondary?: string | null;
  phone_other?: string | null;
  mail_street_address?: string | null;
  mail_city?: string | null;
  mail_state?: string | null;
  mail_zip_code?: string | null;
  property_street_address?: string;
  property_city?: string;
  property_zip_code?: string;
  property_county?: string | null;
  loan_purpose?: string;
  property_use?: string;
  property_value?: string;
  desired_loan_amount?: string | null;
  second_mortgage_balance?: string;
  first_mortgage_rate?: string;
  credit_rating?: string;
  fico_score?: number | null;
  cash_out?: string;
  first_time_buyer?: string | null;
  estimated_down_payment?: string;
  ltv?: string | null;
  monthly_income?: string | null;
  employment_status?: string | null;
  employer_name?: string | null;
  employment_length?: string | null;
  total_credit_card_balance?: string | null;
  total_installment_balance?: string | null;
  monthly_debt_payments?: string | null;
  additional_liens_balance?: string | null;
  lead_id?: string | null;
  ip_address?: string | null;
  universal_lead_id?: string | null;
  campaign_id?: string | null;
  tu_trigger_date?: string | null;
  tu_duplicate_count?: number | null;
  status?: string;
}

export type SharkTankLead = {
  id: number;
  global_id: string;
  lead_id: string;
  tu_pk: string | null;
  first_name: string;
  middle_name: string | null;
  last_name: string;
  suffix: string | null;
  email: string;
  dob: string | null;
  veteran: boolean;
  credit: string | null;
  marital_status: string | null;
  first_name_b2: string | null;
  last_name_b2: string | null;
  address: string;
  city: string;
  state: string;
  zip_code: string;
  home_phone: string;
  cell_phone: string;
  property_use: string;
  property_type: string;
  loan_purpose: string;
  mortgage_balance: string;
  second_mortgage_balance: string;
  desired_loan_amount: string;
  estimated_value: string;
  lead_source: string;
  ulid: string | null;
  status: string;
  assigned_to: string | null;
  assigned_at: string | null;
  updated_at: string;
  created_at: string;
};


export interface CombinedLeadData {
  id: number;
  global_id: string | null;
  lead_id: string | null;
  tu_pk: string | null;
  first_name: string | null;
  middle_name: string | null;
  last_name: string | null;
  suffix: string | null;
  email: string | null;
  dob: Date | null;
  veteran: boolean | null;
  credit: string | null;
  marital_status: string | null;
  first_name_b2: string | null;
  last_name_b2: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip_code: string | null;
  home_phone: string | null;
  cell_phone: string | null;
  property_use: string | null;
  property_type: string | null;
  loan_purpose: string | null;
  mortgage_balance: number | null;
  second_mortgage_balance: number | null;
  desired_loan_amount: number | null;
  estimated_value: number | null;
  lead_source: string | null;
  ulid: string | null;
  status: string | null;
  assigned_to: string | null;
  assigned_at: Date | null;
  updated_at: Date | null;
  created_at: Date | null;
}