export interface DBPipelineLead {
  id?: number;
  lead_id?: number;
  assigned_to?: string;
  first_name?: string | null;
  middle_name?: string | null;
  last_name?: string | null;
  salutation?: string | null;
  phone?: string | null;
  home_phone?: string | null;
  credit_rating?: string | null;
  time_since_contact?: string | null;
  email?: string | null;
  veteran?: string | null;
  lead_status?: string;
  first_name_b2?: string | null;
  middle_name_b2?: string | null;
  last_name_b2?: string | null;
  salutation_b2?: string | null;
  mobile_phone_b2?: string | null;
  home_phone_b2?: string | null;
  primary_email_b2?: string | null;
  address?: string | null;
  po_box?: string | null;
  city?: string | null;
  state?: string | null;
  postal_code?: string | null;
  country?: string | null;
  current_lender?: string | null;
  mortgage_balance?: number | null;
  mortgage_payment?: number | null;
  estimated_value?: number | null;
  loan_type?: string | null;
  ltv?: number | null;
  desired_loan_amount?: number | null;
  cash_out?: number | null;
  rate?: number | null;
  loan_purpose?: string | null;
  mtg_payment_2?: number | null;
  mtg_balance_2?: number | null;
  mtg_type_3?: string | null;
  mtg_term_3?: string | null;
  mtg_balance_3?: number | null;
  utilization_ratio?: number | null;
  opendate?: string | null;
  property_use?: string | null;
  property_type?: string | null;
  last_caller?: string | null;
  last_call_time?: string | null;
  lead_source?: string | null;
  suffix?: string | null;
  ssn?: string | null;
  birth_date?: string | null;
  phone_secondary?: string | null;
  phone_other?: string | null;
  mail_street_address?: string | null;
  mail_city?: string | null;
  mail_state?: string | null;
  mail_zip_code?: string | null;
  property_street_address?: string | null;
  property_city?: string | null;
  property_state?: string | null;
  property_zip_code?: string | null;
  property_county?: string | null;
  property_value?: number | null;
  first_mortgage_balance?: number | null;
  second_mortgage_balance?: number | null;
  first_mortgage_rate?: number | null;
  fico_score?: number | null;
  first_time_buyer?: string | null;
  estimated_down_payment?: number | null;
  monthly_income?: number | null;
  employment_status?: string | null;
  employer_name?: string | null;
  employment_length?: string | null;
  total_credit_card_balance?: number | null;
  total_installment_balance?: number | null;
  monthly_debt_payments?: number | null;
  additional_liens_balance?: number | null;
  ip_address?: string | null;
  universal_lead_id?: string | null;
  campaign_id?: string | null;
  tu_trigger_date?: string | null;
  tu_duplicate_count?: number | null;
  status?: string;
  created_at?: string;
  updated_at?: string;
  username?: string;
  created_date?: string | null;
  rid?: string | null;
  request_id?: string | null;
  desired_rate_type?: string | null;
  user_text1?: string | null;
  current_fha_loan?: string | null;
  originated_before?: string | null;
  signed_contract?: string | null;
  found_home?: string | null;
  purch_agreement?: string | null;
  specials?: string | null;
  method?: string | null;
  adnetwork?: string | null;
  blockclient?: string | null;
  current_va_loan?: string | null;
  age_62_or_older?: string | null;
}

export type PipelineLead = {
  id?: number;
  lead_id?: string;
  first_name?: string;
  middle_name?: string;
  last_name?: string;
  suffix?: string;
  email?: string;
  dob?: string;
  veteran?: boolean;
  credit?: string;
  marital_status?: string;
  first_name_b2?: string;
  last_name_b2?: string;
  address?: string;
  city?: string;
  state?: string;
  zip_code?: string;
  home_phone?: string;
  cell_phone?: string;
  property_use?: string;
  property_type?: string;
  loan_purpose?: string;
  mortgage_balance?: number;
  second_mortgage_balance?: number;
  desired_loan_amount?: number;
  estimated_value?: number;
  lead_source?: string;
  lead_status?: string;
  status?: string;
  ulid?: string;
  created_at?: string;
  updated_at?: string;
  exported?: boolean;
};


export type LowerMyBillsLead = {
  workPhoneExt1?: string;
  workPhoneExt2?: string;
  contactTime?: string;
  grossMonthlyIncome?: number;
  occupationalStatus?: string;
  employerName?: string;
  employmentLength?: string;
  leadID?: string;
  ipAddress?: string;
  firstTimeBuyer?: boolean;
  homeOwner?: boolean;
  needPurchaseREAgent?: string;
  reAgentName?: string;
  reAgentPhone?: string;
  needSellingREAgent?: string;
  consumerComments?: string;
  additionalInformation?: string;
};

export type FreeRateUpdateLead = {
  requestID?: string;
  currentFHALoan?: string;
  currentVALoan?: string;
  age62orOlder?: string;
  price?: number;
};

export type TransUnionLead = {
  triggerDate?: string;
  monthsSinceMostRecentMortgage?: number;
  numMortgageTrades30DaysPastDue?: number;
  highCreditAmountMostRecentMortgage?: number;
  numMonthlyPaymentsMostRecentMortgage?: number;
  monthlyPaymentAmountMostRecentMortgage?: number;
  numRemainingPaymentsMostRecentMortgage?: number;
  openDateMostRecentMortgage?: string;
  currentBalance2ndMostRecentMortgage?: number;
  highCreditAmount2ndMostRecentMortgage?: number;
  openDate2ndMostRecentMortgage?: string;
  monthlyPaymentAmount2ndMostRecentMortgage?: number;
  numRemainingPayments2ndMostRecentMortgage?: number;
  loanType2ndMostRecentMortgage?: string;
  currentBalance3rdMostRecentMortgage?: number;
  highCreditAmount3rdMostRecentMortgage?: number;
  openDate3rdMostRecentMortgage?: string;
  monthlyPaymentAmount3rdMostRecentMortgage?: number;
  numRemainingPayments3rdMostRecentMortgage?: number;
  loanType3rdMostRecentMortgage?: string;
  currentBalanceMostRecentHomeEquity?: number;
  currentBalance2ndMostRecentHomeEquity?: number;
  currentBalance3rdMostRecentHomeEquity?: number;
  ratioOpenBankcardBalanceCreditLine?: number;
  totalBalanceOpenRevolvingTrades?: number;
  totalBalanceBankInstallmentTrades?: number;
};



